/*
 * This is sample code generated by rpcgen.
 * These are only templates and you can use them
 * as a guideline for developing your own functions.
 */

#include "app.h"
#include <string.h>

//Funkcja konwertujaca otrzymany od clienta tekst na hex:
void printInputInHex(char buffer[50], int numberOfSigns){
    char textFromClientInHex[100];
    for(int i = 0, j = 0; i < numberOfSigns; i++, j+=2)
        sprintf(textFromClientInHex + j, "%02x", buffer[i] & 0xff);
    printf("\tPo konwersji (hex): %s\n", textFromClientInHex);
    bzero(textFromClientInHex, 100);
}

wyjscie *
obliczenia_1_svc(wejscie *argp, struct svc_req *rqstp)
{
        static wyjscie  result;

        /*
         * insert server code here
         */
        printInputInHex(argp->text, strlen(argp->text));
        return &result;
}