/*
 * Please do not edit this file.
 * It was generated using rpcgen.
 */

#include "app.h"

bool_t
xdr_wejscie (XDR *xdrs, wejscie *objp)
{
        register int32_t *buf;

        int i;
         if (!xdr_int (xdrs, &objp->x1))
                 return FALSE;
         if (!xdr_int (xdrs, &objp->x2))
                 return FALSE;
         if (!xdr_vector (xdrs, (char *)objp->text, 50,
                sizeof (char), (xdrproc_t) xdr_char))
                 return FALSE;
        return TRUE;
}

bool_t
xdr_wyjscie (XDR *xdrs, wyjscie *objp)
{
        register int32_t *buf;

        int i;

        if (xdrs->x_op == XDR_ENCODE) {
                buf = XDR_INLINE (xdrs, 3 * BYTES_PER_XDR_UNIT);
                if (buf == NULL) {
                         if (!xdr_int (xdrs, &objp->suma))
                                 return FALSE;
                         if (!xdr_int (xdrs, &objp->roznica))
                                 return FALSE;
                         if (!xdr_int (xdrs, &objp->iloczyn))
                                 return FALSE;

                } else {
                IXDR_PUT_LONG(buf, objp->suma);
                IXDR_PUT_LONG(buf, objp->roznica);
                IXDR_PUT_LONG(buf, objp->iloczyn);
                }
                 if (!xdr_vector (xdrs, (char *)objp->text, 50,
                        sizeof (char), (xdrproc_t) xdr_char))
                         return FALSE;
                return TRUE;
        } else if (xdrs->x_op == XDR_DECODE) {
                buf = XDR_INLINE (xdrs, 3 * BYTES_PER_XDR_UNIT);
                if (buf == NULL) {
                         if (!xdr_int (xdrs, &objp->suma))
                                 return FALSE;
                         if (!xdr_int (xdrs, &objp->roznica))
                                 return FALSE;
                         if (!xdr_int (xdrs, &objp->iloczyn))
                                 return FALSE;

                } else {
                objp->suma = IXDR_GET_LONG(buf);
                objp->roznica = IXDR_GET_LONG(buf);
                objp->iloczyn = IXDR_GET_LONG(buf);
                }
                 if (!xdr_vector (xdrs, (char *)objp->text, 50,
                        sizeof (char), (xdrproc_t) xdr_char))
                         return FALSE;
         return TRUE;
        }

         if (!xdr_int (xdrs, &objp->suma))
                 return FALSE;
         if (!xdr_int (xdrs, &objp->roznica))
                 return FALSE;
         if (!xdr_int (xdrs, &objp->iloczyn))
                 return FALSE;
         if (!xdr_vector (xdrs, (char *)objp->text, 50,
                sizeof (char), (xdrproc_t) xdr_char))
                 return FALSE;
        return TRUE;
}